### ISSUE TITLE
Example not working out of the box

### ISSUE THREAD

**Issue by pachacamac** [derhuerst/fetch-bvg-occupancy#1]
Awesome module! Had to adapt the example code like so to make it work:

File had to be a module e.g. `index.mjs`

```javascript
import {scrapeLines, scrapeOccupancies} from 'fetch-bvg-occupancy'; // <-- change require to import

const lines = await scrapeLines()
console.log('lines', ...lines)

const occupancies = await scrapeOccupancies(lines[0])
console.log(occupancies)
```

Question: Do you know how to get similar information for S-Bahn/U-Bahn?

**Comment by derhuerst** [comment]
> Had to adapt the example code like so to make it work: File had to be a module e.g. `index.mjs`

I cannot reproduce this issue:

```shell
node -v
# v16.5.0
node example.js
# lines:
# 100 101 104 108 110 112 114 122 123 124 125 130 131 133 134 135 137 139 140 142 147 150 154 160 164 166 169 175 179 187 191 192 194 197 200 221 240 245 247 248 249 255 256 260 269 271 275 277 282 291 294 296 300 371 372 377 395 398 399 744 M19 M21 M27 M29 M32 M36 M41 M44 M45 M46 M49 M76 M82 X10 X21 X33 X34 X54 X69 X83 12 16 18 21 27 37 50 60 61 67 68 M1 M2 M5 M6 M8 M10 M13 M17 U1 undefined undefined undefined undefined undefined undefined
# …
```

Which version of Node.js are you trying to run `example.js` with?

> Question: Do you know how to get similar information for S-Bahn/U-Bahn?

They do have one U-Bahn line, U1, in the Power BI report scraped by this package; Maybe they'll add more soon!

I don't know where do get similar data about S-Bahn lines.

**Comment by pachacamac** [comment]
Ah my fault. Node Version v14.15.4, was on the wrong nvm setting :)

I thought google maps sometimes showed occupancy .. at least they're sometimes asking to report it. But now sadly I can't get it to show up.

**Comment by derhuerst** [comment]
> I thought google maps sometimes showed occupancy .. at least they're sometimes asking to report it. But now sadly I can't get it to show up.

I don't know anything about how it works underneath, but I assume, that it's purely crowdsourced data. Crowdsourcing such information, just like they ask for heat, feeling of safety, etc. seems like the obvious move for a global-coverage-and-automation-before-detailed-local-information company like Google.

BTW: [iRail in Belgium](https://irail.be) has been doing this for years, but I assume that they don't have enough users. Setting up an app-/service-agnostic thingy for this might make it more successful, like [OpenCellID](https://opencellid.org/) or the (semi-open) [Mozilla Location Service](https://location.services.mozilla.com).
